[GLOBAL]
pants_version = "2.20.0"
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.docformatter",
  "pants.backend.experimental.visibility",
]
pythonpath = ["%(buildroot)s/pants-plugins"]
build_file_prelude_globs = ["pants-plugins/macros.py"]

[anonymous-telemetry]
enabled = true
repo_id = "e35b0560-cd35-11ed-90cd-3887d50cfd0f"

[python-infer]
unowned_dependency_behavior = "error"
use_rust_parser = true

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true

[python.resolves]
python-default = "3rdparty/requirements.lock"
python-dev = "3rdparty/requirements-dev.lock"
python-test = "3rdparty/requirements-test.lock"

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[cli.alias]
build = "fmt lint test update-build-files ::"
